### ISSUE TITLE
Exploring Factors Affecting the Evaluation of Coffee Quality

### ISSUE THREAD

**Issue by 1162259403WXR** [Zoey-2024/DAS-Group-13#1]
- [x] Yingying Zhuo - #2 
- [x] Yingying Zhuo - #3 
- [x] Xuran Wang - #4 
- [x] Xuran Wang - #5 
- [x] Yuxuan Li - #6
- [x] Yuxuan Li - #7

**Comment by Zoey-2024** [comment]
All finished
